/**
 * The one conversation shape every external source is normalized into.
 *
 * Keeping a single intermediate shape is what makes the DSH side simple: the
 * log builder never learns what Cursor or Codex is, and a new source only has
 * to produce this.
 *
 * @module @alex/dsh-session-import/conversation
 */

import { createHash } from 'node:crypto';

/**
 * Create an empty conversation accumulator.
 * @param init - source identity and workspace facts.
 * @returns a mutable conversation record.
 */
export function newConversation(init) {
  return {
    source: init.source,
    id: init.id,
    locator: init.locator,
    title: init.title ?? '',
    cwd: init.cwd ?? undefined,
    createdAt: init.createdAt ?? 0,
    updatedAt: init.updatedAt ?? init.createdAt ?? 0,
    meta: init.meta ?? {},
    messages: [],
  };
}

/**
 * Normalize a message timestamp to epoch milliseconds.
 * @param value - ISO string, epoch milliseconds, or epoch seconds.
 * @param fallback - value used when `value` carries no usable time.
 * @returns epoch milliseconds.
 */
export function toMillis(value, fallback = 0) {
  if (typeof value === 'number' && Number.isFinite(value)) {
    if (value <= 0) return fallback;
    // Seconds are still in use by some stores; anything below the year 2001 in
    // milliseconds is far more likely to be seconds than a real timestamp.
    return value < 1e12 ? Math.round(value * 1000) : Math.round(value);
  }
  if (typeof value === 'string' && value.length > 0) {
    const parsed = Date.parse(value);
    if (Number.isFinite(parsed)) return parsed;
  }
  return fallback;
}

/** Tags whose content is conductor scaffolding rather than a human prompt. */
const SYNTHETIC_PATTERNS = [
  /^<(?:system-reminder|command-name|command-message|command-args|local-command-stdout|local-command-caveat|user-prompt-submit-hook)[\s>]/i,
  /^<(?:environment_context|recommended_plugins|app-context|multi_agent_mode|user_instructions|turn_aborted|INSTRUCTIONS)[\s>]/i,
  /^# AGENTS\.md instructions\b/i,
  /^# Files mentioned by the user:/i,
  /^Caveat: The messages below were generated by the user while running local commands/i,
  /^\[Request interrupted by user/i,
  /^<system_notification>/i,
];

/** Known wrapper tags stripped out of an otherwise human message. */
const REMINDER_TAGS = ['system-reminder', 'system_notification'];

/**
 * Whether a message is conductor scaffolding this importer should drop.
 *
 * Imported sessions are read by a human and later replayed to a model; a wall
 * of `<system-reminder>` skill catalogs is noise in both. The prompt the person
 * actually typed is kept, including when it has reminders appended.
 * @param text - the raw message text, already trimmed.
 * @returns true when the whole message is scaffolding.
 */
export function isSyntheticText(text) {
  const trimmed = text.trim();
  if (trimmed.length === 0) return true;
  return SYNTHETIC_PATTERNS.some((pattern) => pattern.test(trimmed));
}

/**
 * Remove wrapper blocks and harness-injected side channels from a human
 * message while keeping the prose the person wrote.
 * @param text - raw message text.
 * @returns cleaned text, possibly empty.
 */
export function stripInjectedBlocks(text) {
  let out = text;
  for (const tag of REMINDER_TAGS) {
    out = out.replace(new RegExp(`<${tag}>[\\s\\S]*?</${tag}>`, 'gi'), '');
  }
  out = out.replace(/<local-command-stdout>[\s\S]*?<\/local-command-stdout>/gi, '');
  out = out.replace(/<INSTRUCTIONS>[\s\S]*?<\/INSTRUCTIONS>/gi, '');
  out = out.replace(/\n{3,}/g, '\n\n');
  return out.trim();
}

/**
 * Flatten a source content value to plain text.
 *
 * Claude stores `[{type:'text'}]`, Codex stores `input_text` / `output_text`,
 * and a few records are a bare string. One helper keeps scan and read aligned.
 * @param content - a string or a block array.
 * @returns concatenated text, possibly empty.
 */
export function plainTextOf(content) {
  if (typeof content === 'string') return content;
  if (!Array.isArray(content)) return '';
  const parts = [];
  for (const block of content) {
    if (block === null || typeof block !== 'object') continue;
    if (typeof block.text !== 'string') continue;
    if (block.type === undefined || block.type === 'text' || block.type === 'input_text' || block.type === 'output_text') {
      parts.push(block.text);
    }
  }
  return parts.join('\n');
}

/**
 * Title a listing from raw source text, ignoring scaffolding and folder names.
 * @param text - candidate title or first prompt.
 * @param cwd - workspace path the conversation belongs to.
 * @returns a usable title, or empty.
 */
export function promptTitle(text, cwd) {
  const cleaned = stripInjectedBlocks(String(text ?? ''));
  if (isSyntheticText(cleaned)) return '';
  return usableTitle(cleaned.replace(/\s+/g, ' '), cwd);
}

/**
 * Split a leading `<think>`-style reasoning prefix out of assistant text.
 *
 * Claude Code writes extended thinking as a text block wrapped in `<think>`;
 * every other source carries reasoning as its own block. Normalizing here means
 * the log builder has one rule for both.
 * @param text - one assistant text block.
 * @returns reasoning and visible text, either possibly empty.
 */
export function splitThinking(text) {
  const match = /^<(think|thinking)>([\s\S]*?)<\/\1>\s*/i.exec(text);
  if (match === null) return { reasoning: '', text };
  return { reasoning: match[2].trim(), text: text.slice(match[0].length).trim() };
}

/**
 * Append one conversation message, collapsing adjacent messages of the same
 * role into a single turn.
 *
 * Cursor stores one bubble per model step, so a single answer arrives as a
 * dozen assistant bubbles. Left alone that becomes a dozen one-step turns and a
 * transcript that reads like a log file; merged, the imported session reads the
 * way the original conversation did.
 * @param conversation - conversation being built.
 * @param role - `user` or `assistant`.
 * @param text - message text, already cleaned.
 * @param options - optional reasoning text and timestamp.
 */
export function pushMessage(conversation, role, text, options = {}) {
  const trimmed = typeof text === 'string' ? text.trim() : '';
  const reasoning = typeof options.reasoning === 'string' ? options.reasoning.trim() : '';
  if (trimmed.length === 0 && reasoning.length === 0) return;
  if (role !== 'user' && role !== 'assistant') return;
  const time = options.time ?? 0;
  const last = conversation.messages[conversation.messages.length - 1];
  if (last !== undefined && last.role === role) {
    last.parts.push({ text: trimmed, reasoning });
    if (time > 0 && last.time === 0) last.time = time;
    return;
  }
  conversation.messages.push({ role, parts: [{ text: trimmed, reasoning }], time });
}

/**
 * Keep a source title only when it is a real conversation name.
 *
 * Cursor often leaves `name` empty. Claude's `custom-title` and a few Cursor
 * tabs reuse the workspace folder as the label. Those are not titles — the
 * source's generated name (`ai-title`, Cursor `name`) or the first human
 * prompt is.
 * @param title - source-provided name.
 * @param cwd - workspace path the conversation belongs to.
 * @returns a usable title, or empty.
 */
export function usableTitle(title, cwd) {
  const text = String(title ?? '')
    .trim()
    .replace(/\s+/g, ' ');
  if (text.length === 0) return '';
  const base = typeof cwd === 'string' && cwd.length > 0 ? cwd.replace(/[/\\]+$/, '').split(/[/\\]/).pop() : '';
  if (base && text.toLowerCase() === base.toLowerCase()) return '';
  return text;
}

/**
 * Derive a stable title for an imported session.
 *
 * An imported session gets an explicit `session/title` event, so this is the
 * last chance to be legible: the source's own name wins, then the first human
 * prompt, then a placeholder naming the origin.
 * @param conversation - completed conversation.
 * @returns a single-line title.
 */
export function deriveTitle(conversation) {
  const explicit = usableTitle(conversation.title, conversation.cwd);
  if (explicit.length > 0) return truncate(explicit, 120);
  const firstUser = conversation.messages.find((message) => message.role === 'user');
  if (firstUser !== undefined) {
    const text = firstUser.parts.map((part) => part.text).join(' ').replace(/\s+/g, ' ').trim();
    if (text.length > 0) return truncate(text, 120);
  }
  return `Imported ${conversation.source} session`;
}

/** Bound a title without cutting a surrogate pair in half. */
function truncate(text, max) {
  if (text.length <= max) return text;
  return `${text.slice(0, max - 1).trimEnd()}…`;
}

/**
 * Stable identity for one imported message.
 *
 * The log's own message ids must be unique within the session; deriving them
 * from the source id and position keeps a re-import of the same conversation
 * byte-identical, which is what makes "skip what is already imported" checkable
 * rather than guessed.
 * @param source - source id.
 * @param externalId - the source's session id.
 * @param index - message position.
 * @returns a 32-character hex id.
 */
export function messageIdFor(source, externalId, index) {
  return createHash('sha256').update(`${source}:${externalId}:${index}`).digest('hex').slice(0, 32);
}

/** The role a normalized message carries. */
export const ROLES = ['user', 'assistant'];
