/** Knowledge-studio copy for languages beyond the built-in zh/en pair. */

export const KS = {
  'zh-Hant': {
    trigger: '知識庫',
    'trigger.on': '知識庫（已進入）',
    'trigger.off': '知識庫（未進入）',
    'trigger.open': '打開知識庫',
    'trigger.back': '返回工作區',
    settings: '知識庫設定',
    'settings.new': '設定新知識庫',
    'settings.close': '關閉',
    'settings.done': '完成',
    'settings.name': '名稱',
    'settings.folder': '庫資料夾（索引在這裡，不會改你的資料）',
    'settings.indexReady': '索引已建：{chunks} 段 · {files} 個檔案。向量在庫資料夾裡的 index/。',
    'settings.noVectors': '分塊在，但還沒有向量檔。請再點一次「更新索引」。',
    'settings.noIndex': '還沒有向量索引。點「更新索引」建構。',
    'settings.openFolder': '打開庫資料夾',
    'settings.openIndex': '打開索引資料夾',
    'settings.readonly': '資料唯讀引用，原檔不會被改動。',
    'settings.managed': '自帶知識庫：資料就在這個資料夾裡。也可以再掛外部資料。',
    'settings.sources': '資料',
    'settings.sourcesN': '資料 {n} 項',
    'settings.noSources': '還沒有資料。加入檔案或資料夾後，索引會唯讀它們。',
    'settings.source': '資料',
    'settings.open': '打開',
    'settings.remove': '移除',
    'settings.add': '加入檔案或資料夾',
    'settings.loading': '正在讀取知識庫…',
    'settings.rebuildHint': '更新索引只補新增或改過的檔案。',
    'settings.rebuild': '更新索引',
    'settings.building': '資料已掛上，正在建構索引。建好之前不能提問，否則搜不到這些資料。',
    'docs.compare': '檢索對比',
    'docs.compareLong': '檢索對比說明',
    'docs.github': 'GitHub',
    'docs.site': '官網',
    'source.ready': '已檢索',
    'source.loading': '正在檢索本庫…',
    'source.error': '檢索失敗，仍按原問題發送',
    'source.refuse': '本庫沒有足夠相關的內容',
    'source.openHint': '點擊在側欄預覽，⌥點擊在資料夾中顯示',
    'source.close': '關閉檢索資訊',
    'source.vaultFiles': '庫內資料',
    'phase.extract': '正在提取文字',
    'phase.load': '正在載入向量模型',
    'phase.embed': '正在生成向量',
    'phase.write': '正在寫入索引',
    'phase.update': '正在更新索引',
    'log.model': '正在載入向量模型…',
    'log.embed': '正在生成向量…',
    'log.scan': '正在掃描資料…',
    'log.prepare': '正在準備索引…',
    'log.current': '資料沒有變化，索引已是最新。',
    'log.wrote': '索引已寫好。',
    'log.empty': '沒有可索引的資料。',
    'log.updating': '正在更新索引…',
    'gate.title': '索引還在建構，完成後才能提問',
    'gate.wait': '請等建構完成再提問',
    'gate.waitPct': '請等建構完成再提問  {pct}%',
    'gate.none': '這個庫還沒有索引，先等建構完成再提問',
    'toast.building': '正在建構「{name}」',
    'toast.ready': '索引已建好，可以開始提問了。',
    'toast.cancelled': '已取消更新',
    'toast.failed': '更新失敗',
    'toast.scanning': '正在掃描變更並更新索引…',
    'toast.close': '關閉',
    'toast.cancel': '取消更新',
  },
  ja: {
    trigger: 'ナレッジ',
    'trigger.on': 'ナレッジ（表示中）',
    'trigger.off': 'ナレッジ（未表示）',
    'trigger.open': 'ナレッジを開く',
    'trigger.back': 'ワークスペースに戻る',
    settings: 'ナレッジ設定',
    'settings.new': '新しいナレッジを設定',
    'settings.close': '閉じる',
    'settings.done': '完了',
    'settings.name': '名前',
    'settings.folder': 'ライブラリフォルダ（索引はここにあります。元の資料は変更しません）',
    'settings.indexReady': '索引済み：{chunks} チャンク · {files} ファイル。ベクトルはライブラリの index/ にあります。',
    'settings.noVectors': 'チャンクはありますがベクトルがありません。「索引を更新」をもう一度押してください。',
    'settings.noIndex': 'ベクトル索引がありません。「索引を更新」で構築します。',
    'settings.openFolder': 'ライブラリフォルダを開く',
    'settings.openIndex': '索引フォルダを開く',
    'settings.readonly': '資料は読み取り専用です。元のファイルは変更されません。',
    'settings.managed': '付属のナレッジです。このフォルダ内の資料に、外部資料を追加できます。',
    'settings.sources': '資料',
    'settings.sourcesN': '資料 {n} 件',
    'settings.noSources': '資料がありません。ファイルまたはフォルダを追加すると、索引はそれらを読み取り専用で参照します。',
    'settings.source': '資料',
    'settings.open': '開く',
    'settings.remove': '削除',
    'settings.add': 'ファイルまたはフォルダを追加',
    'settings.loading': 'ナレッジを読み込み中…',
    'settings.rebuildHint': '索引の更新は、新規または変更されたファイルだけを補います。',
    'settings.rebuild': '索引を更新',
    'settings.building': '資料を追加しました。索引の構築中です。完了するまで質問すると見つかりません。',
    'docs.compare': '検索の比較',
    'docs.compareLong': '検索比較の説明',
    'docs.github': 'GitHub',
    'docs.site': '公式サイト',
    'source.ready': '検索済み',
    'source.loading': 'このライブラリを検索中…',
    'source.error': '検索に失敗したため、元の質問のまま送信します',
    'source.refuse': 'このライブラリに十分な関連内容がありません',
    'source.openHint': 'クリックでサイドバー表示、⌥クリックでフォルダに表示',
    'source.close': '検索情報を閉じる',
    'source.vaultFiles': 'ライブラリ内の資料',
    'phase.extract': 'テキストを抽出中',
    'phase.load': '埋め込みモデルを読み込み中',
    'phase.embed': 'ベクトルを生成中',
    'phase.write': '索引を書き込み中',
    'phase.update': '索引を更新中',
    'log.model': '埋め込みモデルを読み込み中…',
    'log.embed': 'ベクトルを生成中…',
    'log.scan': '資料をスキャン中…',
    'log.prepare': '索引を準備中…',
    'log.current': '資料に変更はないため、索引は最新です。',
    'log.wrote': '索引を書き込みました。',
    'log.empty': '索引できる資料がありません。',
    'log.updating': '索引を更新中…',
    'gate.title': '索引を構築中です。完了するまで質問できません',
    'gate.wait': '構築が終わるまで待ってから質問してください',
    'gate.waitPct': '構築が終わるまで待ってから質問してください  {pct}%',
    'gate.none': 'このライブラリにはまだ索引がありません。構築が終わってから質問してください',
    'toast.building': '「{name}」を構築中',
    'toast.ready': '索引ができました。質問を始められます。',
    'toast.cancelled': '更新をキャンセルしました',
    'toast.failed': '更新に失敗しました',
    'toast.scanning': '変更をスキャンして索引を更新中…',
    'toast.close': '閉じる',
    'toast.cancel': '更新をキャンセル',
  },
  ko: {
    trigger: '지식 베이스',
    'trigger.on': '지식 베이스(표시 중)',
    'trigger.off': '지식 베이스(숨김)',
    'trigger.open': '지식 베이스 열기',
    'trigger.back': '작업 공간으로 돌아가기',
    settings: '지식 베이스 설정',
    'settings.new': '새 지식 베이스 구성',
    'settings.close': '닫기',
    'settings.done': '완료',
    'settings.name': '이름',
    'settings.folder': '라이브러리 폴더(인덱스는 여기에 있습니다. 원본은 바꾸지 않습니다)',
    'settings.indexReady': '인덱스 완료: {chunks}개 청크 · {files}개 파일. 벡터는 라이브러리의 index/에 있습니다.',
    'settings.noVectors': '청크는 있지만 벡터 파일이 없습니다. 「인덱스 업데이트」를 다시 누르세요.',
    'settings.noIndex': '벡터 인덱스가 없습니다. 「인덱스 업데이트」로 만드세요.',
    'settings.openFolder': '라이브러리 폴더 열기',
    'settings.openIndex': '인덱스 폴더 열기',
    'settings.readonly': '자료는 읽기 전용입니다. 원본 파일은 바뀌지 않습니다.',
    'settings.managed': '기본 지식 베이스입니다. 이 폴더의 자료에 외부 자료를 더할 수 있습니다.',
    'settings.sources': '자료',
    'settings.sourcesN': '자료 {n}개',
    'settings.noSources': '자료가 없습니다. 파일이나 폴더를 추가하면 인덱스가 읽기 전용으로 참조합니다.',
    'settings.source': '자료',
    'settings.open': '열기',
    'settings.remove': '제거',
    'settings.add': '파일 또는 폴더 추가',
    'settings.loading': '지식 베이스를 읽는 중…',
    'settings.rebuildHint': '인덱스 업데이트는 새 파일이나 바뀐 파일만 보완합니다.',
    'settings.rebuild': '인덱스 업데이트',
    'settings.building': '자료를 연결했습니다. 인덱스를 만드는 중입니다. 끝나기 전에 질문하면 찾을 수 없습니다.',
    'docs.compare': '검색 비교',
    'docs.compareLong': '검색 비교 설명',
    'docs.github': 'GitHub',
    'docs.site': '공식 사이트',
    'source.ready': '검색됨',
    'source.loading': '이 라이브러리를 검색하는 중…',
    'source.error': '검색에 실패해 원래 질문 그대로 보냅니다',
    'source.refuse': '이 라이브러리에 관련 내용이 충분하지 않습니다',
    'source.openHint': '클릭하면 사이드바에서 미리보기, ⌥클릭하면 폴더에서 보기',
    'source.close': '검색 정보 닫기',
    'source.vaultFiles': '라이브러리 자료',
    'phase.extract': '텍스트 추출 중',
    'phase.load': '임베딩 모델 로드 중',
    'phase.embed': '벡터 생성 중',
    'phase.write': '인덱스 기록 중',
    'phase.update': '인덱스 업데이트 중',
    'log.model': '임베딩 모델을 로드하는 중…',
    'log.embed': '벡터를 생성하는 중…',
    'log.scan': '자료를 스캔하는 중…',
    'log.prepare': '인덱스를 준비하는 중…',
    'log.current': '자료가 바뀌지 않아 인덱스가 최신입니다.',
    'log.wrote': '인덱스를 저장했습니다.',
    'log.empty': '인덱싱할 자료가 없습니다.',
    'log.updating': '인덱스를 업데이트하는 중…',
    'gate.title': '인덱스를 만드는 중입니다. 끝난 뒤에 질문하세요',
    'gate.wait': '구축이 끝날 때까지 기다린 뒤 질문하세요',
    'gate.waitPct': '구축이 끝날 때까지 기다린 뒤 질문하세요  {pct}%',
    'gate.none': '이 라이브러리에는 아직 인덱스가 없습니다. 구축이 끝난 뒤 질문하세요',
    'toast.building': '「{name}」을(를) 구축하는 중',
    'toast.ready': '인덱스가 준비되었습니다. 질문을 시작할 수 있습니다.',
    'toast.cancelled': '업데이트를 취소했습니다',
    'toast.failed': '업데이트에 실패했습니다',
    'toast.scanning': '변경 사항을 스캔하고 인덱스를 업데이트하는 중…',
    'toast.close': '닫기',
    'toast.cancel': '업데이트 취소',
  },
  fr: {
    trigger: 'Base de connaissances',
    'trigger.on': 'Base de connaissances (ouverte)',
    'trigger.off': 'Base de connaissances (fermée)',
    'trigger.open': 'Ouvrir la base de connaissances',
    'trigger.back': 'Retour à l’espace de travail',
    settings: 'Paramètres de la base',
    'settings.new': 'Configurer une nouvelle base',
    'settings.close': 'Fermer',
    'settings.done': 'Terminé',
    'settings.name': 'Nom',
    'settings.folder': 'Dossier de la bibliothèque (l’index est ici ; vos fichiers ne sont pas modifiés)',
    'settings.indexReady': 'Index prêt : {chunks} passages · {files} fichiers. Les vecteurs sont dans index/.',
    'settings.noVectors': 'Les passages sont là, mais pas les vecteurs. Relancez « Mettre à jour l’index ».',
    'settings.noIndex': 'Pas encore d’index vectoriel. Cliquez sur « Mettre à jour l’index ».',
    'settings.openFolder': 'Ouvrir le dossier de la bibliothèque',
    'settings.openIndex': 'Ouvrir le dossier d’index',
    'settings.readonly': 'Les sources sont en lecture seule. Les fichiers d’origine ne sont pas touchés.',
    'settings.managed': 'Base fournie : les documents sont dans ce dossier. Vous pouvez aussi ajouter des sources externes.',
    'settings.sources': 'Sources',
    'settings.sourcesN': '{n} sources',
    'settings.noSources': 'Aucune source. Ajoutez des fichiers ou des dossiers ; l’index les lira sans les modifier.',
    'settings.source': 'Source',
    'settings.open': 'Ouvrir',
    'settings.remove': 'Retirer',
    'settings.add': 'Ajouter des fichiers ou dossiers',
    'settings.loading': 'Chargement de la base…',
    'settings.rebuildHint': 'La mise à jour n’ajoute que les fichiers nouveaux ou modifiés.',
    'settings.rebuild': 'Mettre à jour l’index',
    'settings.building': 'Sources ajoutées. L’index se construit. Attendez la fin avant de poser une question.',
    'docs.compare': 'Comparaison de recherche',
    'docs.compareLong': 'Notes sur la comparaison de recherche',
    'docs.github': 'GitHub',
    'docs.site': 'Site officiel',
    'source.ready': 'Trouvé',
    'source.loading': 'Recherche dans cette base…',
    'source.error': 'Échec de la recherche ; la question est envoyée telle quelle',
    'source.refuse': 'Pas assez de contenu pertinent dans cette base',
    'source.openHint': 'Cliquer pour prévisualiser, ⌥-clic pour afficher dans le dossier',
    'source.close': 'Fermer les sources',
    'source.vaultFiles': 'Fichiers de la base',
    'phase.extract': 'Extraction du texte',
    'phase.load': 'Chargement du modèle d’embedding',
    'phase.embed': 'Génération des vecteurs',
    'phase.write': 'Écriture de l’index',
    'phase.update': 'Mise à jour de l’index',
    'log.model': 'Chargement du modèle d’embedding…',
    'log.embed': 'Génération des vecteurs…',
    'log.scan': 'Analyse des sources…',
    'log.prepare': 'Préparation de l’index…',
    'log.current': 'Aucune modification ; l’index est déjà à jour.',
    'log.wrote': 'Index enregistré.',
    'log.empty': 'Rien à indexer.',
    'log.updating': 'Mise à jour de l’index…',
    'gate.title': 'Index en cours de construction ; attendez pour poser une question',
    'gate.wait': 'Attendez la fin de la construction avant de poser une question',
    'gate.waitPct': 'Attendez la fin de la construction avant de poser une question  {pct}%',
    'gate.none': 'Cette base n’a pas encore d’index. Attendez la fin de la construction.',
    'toast.building': 'Construction de « {name} »',
    'toast.ready': 'Index prêt. Vous pouvez poser des questions.',
    'toast.cancelled': 'Mise à jour annulée',
    'toast.failed': 'Échec de la mise à jour',
    'toast.scanning': 'Analyse des changements et mise à jour de l’index…',
    'toast.close': 'Fermer',
    'toast.cancel': 'Annuler la mise à jour',
  },
  es: {
    trigger: 'Base de conocimiento',
    'trigger.on': 'Base de conocimiento (abierta)',
    'trigger.off': 'Base de conocimiento (cerrada)',
    'trigger.open': 'Abrir la base de conocimiento',
    'trigger.back': 'Volver al espacio de trabajo',
    settings: 'Ajustes de la base',
    'settings.new': 'Configurar una base nueva',
    'settings.close': 'Cerrar',
    'settings.done': 'Hecho',
    'settings.name': 'Nombre',
    'settings.folder': 'Carpeta de la biblioteca (el índice está aquí; tus archivos no se modifican)',
    'settings.indexReady': 'Índice listo: {chunks} fragmentos · {files} archivos. Los vectores están en index/.',
    'settings.noVectors': 'Hay fragmentos, pero no vectores. Pulsa otra vez «Actualizar índice».',
    'settings.noIndex': 'Aún no hay índice vectorial. Pulsa «Actualizar índice».',
    'settings.openFolder': 'Abrir la carpeta de la biblioteca',
    'settings.openIndex': 'Abrir la carpeta del índice',
    'settings.readonly': 'Las fuentes son de solo lectura. Los archivos originales no se tocan.',
    'settings.managed': 'Base incluida: los documentos están en esta carpeta. También puedes añadir fuentes externas.',
    'settings.sources': 'Fuentes',
    'settings.sourcesN': '{n} fuentes',
    'settings.noSources': 'No hay fuentes. Añade archivos o carpetas; el índice las leerá sin modificarlas.',
    'settings.source': 'Fuente',
    'settings.open': 'Abrir',
    'settings.remove': 'Quitar',
    'settings.add': 'Añadir archivos o carpetas',
    'settings.loading': 'Cargando la base…',
    'settings.rebuildHint': 'La actualización solo añade archivos nuevos o cambiados.',
    'settings.rebuild': 'Actualizar índice',
    'settings.building': 'Fuentes añadidas. Se está construyendo el índice. Espera a que termine antes de preguntar.',
    'docs.compare': 'Comparación de búsqueda',
    'docs.compareLong': 'Notas sobre la comparación de búsqueda',
    'docs.github': 'GitHub',
    'docs.site': 'Sitio oficial',
    'source.ready': 'Encontrado',
    'source.loading': 'Buscando en esta base…',
    'source.error': 'Falló la búsqueda; se envía la pregunta original',
    'source.refuse': 'No hay suficiente contenido relevante en esta base',
    'source.openHint': 'Clic para previsualizar; ⌥-clic para mostrar en la carpeta',
    'source.close': 'Cerrar fuentes',
    'source.vaultFiles': 'Archivos de la base',
    'phase.extract': 'Extrayendo texto',
    'phase.load': 'Cargando el modelo de embeddings',
    'phase.embed': 'Generando vectores',
    'phase.write': 'Escribiendo el índice',
    'phase.update': 'Actualizando el índice',
    'log.model': 'Cargando el modelo de embeddings…',
    'log.embed': 'Generando vectores…',
    'log.scan': 'Escaneando fuentes…',
    'log.prepare': 'Preparando el índice…',
    'log.current': 'No hubo cambios; el índice ya está al día.',
    'log.wrote': 'Índice guardado.',
    'log.empty': 'No hay nada que indexar.',
    'log.updating': 'Actualizando el índice…',
    'gate.title': 'El índice se está construyendo; espera para preguntar',
    'gate.wait': 'Espera a que termine la construcción antes de preguntar',
    'gate.waitPct': 'Espera a que termine la construcción antes de preguntar  {pct}%',
    'gate.none': 'Esta base aún no tiene índice. Espera a que termine la construcción.',
    'toast.building': 'Construyendo «{name}»',
    'toast.ready': 'Índice listo. Ya puedes preguntar.',
    'toast.cancelled': 'Actualización cancelada',
    'toast.failed': 'Error al actualizar',
    'toast.scanning': 'Escaneando cambios y actualizando el índice…',
    'toast.close': 'Cerrar',
    'toast.cancel': 'Cancelar actualización',
  },
};
